import { StyleSheet } from "react-native";
import { COLORS } from ".";
const styles = StyleSheet.create({
  ImgBackground: {
    width: "100%",
    height: "100%",
    position: "absolute",
    resizeMode: "cover",
  },
  container: {
    flex: 1,
    // backgroundColor: "#161928",
    backgroundColor: "#242424",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  loginContainer: {
    width: "100%",
    height: "100%",
    overflow: "hidden",
    borderRadius: 8,
    color: "#fff",
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "rgba(255, 255, 255, 0.097)",
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderRadius: 15,
    padding: 32,
    // backdropFilter: "blur(10px)",
  },
  loginInput: {
    width: 200,
    // ",
    // border: "0",
    // borderBottom: "2px solid rgba(255,255,255, 0.3)",
    // margin: "20px 0",
    paddingBottom: 10,
    fontSize: 18,
    color: "rgba(255,255,255, 0.8)",
  },
  logcontainer: {
    flex: 1,
    backgroundColor: "#003f5c",
    alignItems: "center",
    justifyContent: "center",
  },
  inputView: {
    width: "80%",
    backgroundColor: "#465881",
    borderRadius: 25,
    height: 50,
    marginBottom: 20,
    justifyContent: "center",
    padding: 5,
  },
  inputText: {
    width: "100%",
    height: "100%",
    flex: 2,
    color: "white",
  },
  forgot: {
    color: "white",
    fontSize: 11,
  },
  loginBtn: {
    width: "80%",
    backgroundColor: "#fb5b5a",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    marginBottom: 10,
  },
  loginText: {
    color: "white",
  },
  loginForm: {
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    // transform: [
    //   { translateX: -50 },
    //   { translateY: -50},

    // ],
  },
  loginImg: {
    width: 120,
    height: 120,
    paddingBottom: 10,
    borderRadius: 100,
    marginBottom: 40,
  },
  myContainer: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "#161928",
    backgroundColor: "#242424",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(0, 0, 0, 0.1)",
    // backdropFilter: "blur(10px)",
    // position: "fixed",
    left: 0,
  },
  titles: {
    marginTop: "10%",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  title: {
    fontSize: 20,
    fontWeight: "500",
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.8)",
  },
  subtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.6)",
  },
  glassButton: {
    height: 40,
    width: "95%",
    // borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 ",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // backdropFilter: "blur(30px)",
    marginTop: 10,
    textTransform: "uppercase",
  },
  circleButton: {
    height: 40,
    width: 40,
    // marginLeft: '47%',
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "#f56390",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "1px solid rgba(255, 255, 255, 0.1)",
    marginTop: 10,
    textTransform: "uppercase",
  },
  sendButton: {
    height: 60,
    width: 60,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(31, 167, 243, 0.37)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "1px solid rgba(255, 255, 255, 0.1)",
    marginTop: 10,
    color: "#1fa7f3",
  },
  payButton: {
    height: 60,
    width: 60,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(240, 50, 84, 0.37)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "1px solid rgba(255, 255, 255, 0.1)",
    marginTop: 10,
    color: "#1fa7f3",
  },
  withdrawButton: {
    height: 60,
    width: 60,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "rgba(26, 162, 112, 0.37)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "1px solid rgba(255, 255, 255, 0.1)",
    marginTop: 10,
    color: "#1fa7f3",
  },
  buttonText: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 17,
    fontWeight: "bold",
  },
  buttonText2: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 12,
    fontWeight: "normal",
  },
  HeaderText: {
    color: "#3b3b3b",
    fontSize: 17,
    fontWeight: "normal",
  },
  HeaderBotton: {
    minWidth: 36,
    height: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    color: "#6236FF",
    position: "relative",
  },
  buttonContainer: {
    flex: 1,
    flexDirection: "column",
    position: "absolute",
    bottom: 10,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingTop: "30%",
  },
  glassPanel: {
    color: "#fff",
    alignItems: "center",
    justifyContent: "center",
    // margin: "40px auto",
    backgroundColor: "rgba(255, 255, 255, 0.097)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderRadius: 15,
    padding: 32,
    width: "80%",
    // backdropFilter: "blur(10px)",
  },
  navigation: {
    // position: "fixed",
    // top: 0,
    // left: 0,
    // width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    borderBottomWidth: 0,
    // display: "flex",
    // flexWrap: "nowrap",
    flexDirection: "row",
    // justifyContent: "space-between",
    // alignItems: "center",
    // flexShrink: 0,
    // height: "58px",
    // padding: "0 30px",
    // whiteSpace: "nowrap",
  },
  cardGroup: {
    width: "98%",
  },
  card: {
    position: "relative",
    height: 270,
    width: "100%",
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    // backdropFilter: "blur(30px)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
    // boxShadow: "0 8px 32px 0 rgba(11, 13, 49, 0.37)",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "1px solid rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  logoimg: {
    top: 35,
    right: 40,
    width: 30,
    height: 30,
    position: "absolute",
  },
  balance: {
    top: 35,
    left: 40,
    width: "50%",
    color: "rgba(255, 255, 255, 0.8)",
    height: 30,
    fontFamily: `"Nunito", sans-serif`,
    fontSize: 20,
    fontWeight: "bold",
    position: "absolute",
  },
  chipimg: {
    top: 120,
    left: 40,
    width: 30,
    height: 30,
    position: "absolute",
  },
  cardnumber: {
    left: 40,
    bottom: 65,
    // fontFamily: `"Nunito", sans-serif`,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "400",
    letterSpacing: 2,
    // textShadow: "0 0 2px rgba(0, 0, 0, 0.6)",
    position: "absolute",
  },
  cardname: {
    fontSize: 8,
    left: 40,
    bottom: 35,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "400",
    letterSpacing: 2,
    // textShadow: "0 0 2px rgba(0, 0, 0, 0.6)",
    position: "absolute",
  },
  cardfrom: {
    fontSize: 8,
    bottom: 35,
    right: 110,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "400",
    letterSpacing: 2,
    // textShadow: "0 0 2px rgba(0, 0, 0, 0.6)",
    position: "absolute",
  },
  cardto: {
    fontSize: 8,
    bottom: 35,
    right: 40,
    color: "rgba(255, 255, 255, 0.8)",
    fontWeight: "400",
    letterSpacing: 2,
    // textShadow: "0 0 2px rgba(0, 0, 0, 0.6)",
    position: "absolute",
  },
  cardring: {
    position: "absolute",
    height: 500,
    width: 500,
    borderRadius: 500 / 2,
    backgroundColor: "transparent",
    borderWidth: 50,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "50px solid rgba(255, 255, 255, 0.1)",
    bottom: -250,
    right: -250,
    // boxSizing: "border-box",
  },
  cardringafter: {
    // content: "",
    position: "absolute",
    height: 600,
    width: 600,
    borderRadius: 600 / 2,
    backgroundColor: "transparent",
    borderWidth: 30,
    borderStyle: "solid",
    borderColor: "rgba(255, 255, 255, 0.1)",
    // border: "30px solid rgba(255, 255, 255, 0.1)",
    bottom: -80,
    right: -110,
    // boxSizing: "border-box",
  },
  buttonGroup: {
    display: "flex",
    flexWrap: "nowrap",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
  },
  ScrollView: {
    marginTop: 50,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  appBottomMenu: {
    minHeight: 56,
    // position: "fixed",
    zIndex: 999,
    width: "100%",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    // borderTopWidth: 1,
    // borderTopStyle: "solid",
    // borderTopColor: "#DCDCE9",
    paddingLeft: 4,
    paddingRight: 4,
    // paddingBottom: "env(safe-area-inset-bottom)",
    flexDirection: "row",
  },
  footerItem: {
    fontSize: 9,
    letterSpacing: 0,
    textAlign: "center",
    width: "20%",
    height: 56,
    lineHeight: 1.2,
    display: "flex",
    alignItems: "center",
    color: "#fff",
    justifyContent: "center",
    position: "relative",
  },
  HeaderItem: {
    textAlign: "center",
    width: "33.333%",
    display: "flex",
    alignItems: "center",
    color: "rgba(255, 255, 255, 0.8)",
    justifyContent: "center",
    position: "relative",
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 6,
    borderColor: COLORS.black,
  },
  profilename: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 20,
    fontWeight: "800",
    marginVertical: 8,
    // alignSelf: "center",
  },
  sectionHeader: {
    fontWeight: "800",
    fontSize: 18,
    color: "#f4f4f4",
    marginTop: 20,
    marginBottom: 5,
  },
  item: {
    margin: 10,
  },
  itemPhoto: {
    width: 200,
    height: 200,
  },
  itemText: {
    color: "rgba(255, 255, 255, 0.5)",
    marginTop: 5,
  },
  escrowLink: {
    backgroundColor: "rgba(255, 255, 255, 0.097)",
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,

    borderRadius: 10,
    paddingTop: 20,
    paddingRight: 24,
    paddingBottom: 20,
    paddingLeft: 24,
    marginBottom: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  escrowDetails: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    lineHeight: 1.2,
  },
  escrowImg: {
    fontSize: 15,
    letterSpacing: 0.004,
    color: "#6236FF",
    lineHeight: 1.2,
    borderRadius: 10,
    width: 48,
    height: 48,
    marginRight: 16,
  },
  escrowRight: {
    fontSize: 15,
    paddingLeft: 10,
  },
  escrowPrice: { fontWeight: "700", color: "rgba(255, 255, 255, 0.5)" },
  a_section: {
    fontSize: 15,
    lineHeight: 1.6,
    letterSpacing: 0.004,
    color: "#8f82a5",
    paddingTop: 0,
    paddingRight: 16,
    paddingBottom: 0,
    paddingLeft: 16,
    marginTop: 24,
  },
  avatarSection: {
    textAlign: "center",
    position: "relative",
    // display: "inline-flex",
  },
  avatarImg: {
    textAlign: "center",
    color: "#6236FF",
    height: 100,
    width: 100,
    borderRadius: 50,
    borderWidth: 5,
    borderStyle: "solid",
    borderColor: "#fff",
    shadowColor: "rgba(0, 0, 0, 0.09)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 3,
  },
  avatarSectionButton: {
    lineHeight: 1.6,
    letterSpacing: 0.004,
    textAlign: "center",
    backgroundColor: "#6236FF",
    color: "#fff",
    width: 32,
    height: 32,
    borderRadius: 32,
    // display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    position: "absolute",
    right: 0,
    bottom: 0,
  },
  listView: {
    // display: "block",
    padding: 0,
    margin: 0,
    lineHeight: 1.3,
    marginLeft: 16,
    marginRight: 16,
    overflow: "hidden",
    // border: 0,
    borderRadius: 10,
    shadowColor: "rgba(11, 13, 49, 0.37)",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    color: "#fff",
    backgroundColor: "#161129",
    borderTopColor: "#2d1f3b",
    borderBottomColor: "#2d1f3b",
  },
  listView_li: {
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    padding: 0,
    minHeight: "auto",
  },
  listView_in: {
    color: "#fff",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  listView_item: {
    color: "#fff",
    paddingTop: 11,
    paddingRight: 16,
    paddingBottom: 11,
    paddingLeft: 16,
    width: "100%",
    minHeight: 50,
    display: "flex",
    alignItems: "center",
  },
  hr: {
    display: "flex",
    // position: "absolute",
    // left: 0,
    // right: 0,
    bottom: 0,
    height: 1,
    width: "90%",
    marginLeft: "5%",
    backgroundColor: "#DCDCE925",
  },
});
const styles2 = StyleSheet.create({
  container: {
    height: 256,
    width: 160,
    backgroundColor: "rgba(59,130,246,1)",
    borderRadius: 12,
    padding: 15,
    margin: 5,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  logoBackground: {
    width: 112,
    height: 112,
    borderRadius: 55,
    backgroundColor: "#E4F0FE",
  },
  logo: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  text: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
    marginVertical: 10,
  },
  button: {
    height: 40,
    width: "100%",
    backgroundColor: "white",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(59,130,246,1)",
  },
  buttonText: {
    color: "rgba(59,130,246,1)",
    fontSize: 17,
    fontWeight: "bold",
  },
});
export { styles, styles2 };
